# Generated by Django 5.2.4 on 2025-08-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ai_SolutionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='admin_reply_sent',
            field=models.BooleanField(default=False, help_text='Mark as true when admin reply email is sent'),
        ),
    ]
