# Generated by Django 5.2.4 on 2025-09-04 01:52

import Ai_SolutionApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ai_SolutionApp', '0003_userrole_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief bio about the user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=Ai_SolutionApp.models.OptimizedImageField(blank=True, help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', null=True, upload_to='profiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=Ai_SolutionApp.models.OptimizedImageField(blank=True, help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', null=True, upload_to='articles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=Ai_SolutionApp.models.OptimizedImageField(help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', upload_to='gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='pastsolution',
            name='image',
            field=Ai_SolutionApp.models.OptimizedImageField(blank=True, help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', null=True, upload_to='solutions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=Ai_SolutionApp.models.OptimizedImageField(blank=True, help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', null=True, upload_to='testimonials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
