# Generated by Django 5.2.4 on 2025-09-14 02:35

import Ai_SolutionApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ai_SolutionApp', '0004_userprofile_bio_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200),
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_hero_image',
            field=models.BooleanField(default=False, help_text='Use as hero background image'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='tags',
            field=models.JSONField(default=list, help_text='Tags for filtering and search'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='thumbnail',
            field=Ai_SolutionApp.models.OptimizedImageField(blank=True, help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', null=True, upload_to='gallery/thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='gallery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=Ai_SolutionApp.models.OptimizedImageField(blank=True, help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', null=True, upload_to='articles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('ai_solutions', 'AI Solutions'), ('team_events', 'Team Events'), ('conferences', 'Conferences'), ('workshops', 'Workshops'), ('office', 'Office'), ('awards', 'Awards'), ('client_meetings', 'Client Meetings'), ('product_demos', 'Product Demos'), ('research', 'Research & Development'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=Ai_SolutionApp.models.OptimizedImageField(help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', upload_to='gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='pastsolution',
            name='image',
            field=Ai_SolutionApp.models.OptimizedImageField(blank=True, help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', null=True, upload_to='solutions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=Ai_SolutionApp.models.OptimizedImageField(blank=True, help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', null=True, upload_to='testimonials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=Ai_SolutionApp.models.OptimizedImageField(blank=True, help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', null=True, upload_to='profiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
