# Generated by Django 5.2.6 on 2025-09-15 04:27

import Ai_SolutionApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ai_SolutionApp', '0005_gallery_alt_text_gallery_is_hero_image_gallery_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Subscriber email address', max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, help_text='When the user subscribed')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subscription is active')),
                ('source', models.CharField(default='website', help_text='Where the subscription came from', max_length=100)),
                ('unsubscribed_at', models.DateTimeField(blank=True, help_text='When the user unsubscribed', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when subscribed', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser information when subscribed')),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=Ai_SolutionApp.models.OptimizedImageField(blank=True, help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', null=True, upload_to='articles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=Ai_SolutionApp.models.OptimizedImageField(help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', upload_to='gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='thumbnail',
            field=Ai_SolutionApp.models.OptimizedImageField(blank=True, help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', null=True, upload_to='gallery/thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='pastsolution',
            name='image',
            field=Ai_SolutionApp.models.OptimizedImageField(blank=True, help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', null=True, upload_to='solutions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=Ai_SolutionApp.models.OptimizedImageField(blank=True, help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', null=True, upload_to='testimonials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=Ai_SolutionApp.models.OptimizedImageField(blank=True, help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', null=True, upload_to='profiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
