# Generated by Django 5.2.6 on 2025-09-18 06:08

import Ai_SolutionApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ai_SolutionApp', '0011_event_featured_image_event_featured_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastsolution',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL as alternative to uploaded image', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=Ai_SolutionApp.models.OptimizedImageField(blank=True, help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', null=True, upload_to='articles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='event',
            name='featured_image',
            field=Ai_SolutionApp.models.OptimizedImageField(blank=True, help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', null=True, upload_to='events/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=Ai_SolutionApp.models.OptimizedImageField(help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', upload_to='gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='thumbnail',
            field=Ai_SolutionApp.models.OptimizedImageField(blank=True, help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', null=True, upload_to='gallery/thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='pastsolution',
            name='image',
            field=Ai_SolutionApp.models.OptimizedImageField(blank=True, help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', null=True, upload_to='solutions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=Ai_SolutionApp.models.OptimizedImageField(blank=True, help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', null=True, upload_to='testimonials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=Ai_SolutionApp.models.OptimizedImageField(blank=True, help_text='Upload PNG, JPEG, or WebP images. Max size: 10MB', null=True, upload_to='profiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
